name: E2E tests workflow
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
env:
  OPENSEARCH_DASHBOARDS_VERSION: 'main'
  OPENSEARCH_VERSION: '3.0.0-SNAPSHOT'
jobs:
  tests:
    name: Run Cypress E2E tests with security
    runs-on: ubuntu-latest
    env:
      # prevents extra Cypress installation progress messages
      CI: 1
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
    steps:
      - id: run-cypress-tests
        uses: ./.github/actions/run-cypress-tests
        with:
          with-security: true
